### ISSUE TITLE
File name shouldn't contain version number

### ISSUE THREAD

**Issue by JuhQ** [varvet/tiny-autocomplete#10]
I don't think the file name should contain version number.
For example at the moment I'm writing this, both examples are pointing to a version (0.4.1) which does not exist. Current version is 0.4.3.

Removing version from file name would also future proof the library for bower etc usage.

The version is already on the file itself and that should be enough.

**Comment by johanhalse** [comment]
Good idea! Implemented and released as [v0.4.4](https://github.com/varvet/tiny-autocomplete/releases/tag/v0.4.4).

**Comment by JuhQ** [comment]
@johanhalse :+1:
