### ISSUE TITLE
suggest list not closing on blur

### ISSUE THREAD

**Issue by moritzschepp** [varvet/tiny-autocomplete#25]
Excellent library, I just found this and its exactly what I was looking for. Thanks for sharing it!

I think I found a small bug: The suggest list doesn't close on blur event. To reproduce, type something into the input, don't select anything and alt-tab to trigger the blur. The focus is on the current input now while the suggest list is still open on the previous input.

I also didn't find a non-hacky way to fix this with a custom blur event handler since I didn't find a way to access the `closeList` function.

**Comment by johanhalse** [comment]
Thanks for the bug report! I'll look into it.

**Comment by johanhalse** [comment]
I've dug into the issue and it's not as easily solved as I had hoped. The blur handler fires before onclick which means that when a user clicks or taps an item in the list, the blur event has closed the list and the click doesn't happen. I experimented with `requestAnimationFrame` but that wasn't reliable and I think the mobile device delay is going to cause us even more headaches going forward. Maybe a long (300ms or so) `setTimeout` would solve it — that seems inelegant though. I'll try to experiment with it.

**Comment by moritzschepp** [comment]
Have a look at this so answer: https://stackoverflow.com/a/37694450/351909 it suggests that `mousedown` is fired before `blur`. Could that be used instead of `click` for menu selection? It would slightly alter the behavior, though.

**Comment by johanhalse** [comment]
Yes, that's probably the most appetizing option. I've added a Cypress test suite and the existing tests for navigating and selecting didn't flinch when I switched to using `mousedown` instead. We'll be moving to version `1.0.0` anyway, so we can document this as a breaking change if anyone's relying on the plugin firing the `click` event. And this plugin isn't in the npm ecosystem yet so there won't be any automatic updates :)

**Comment by moritzschepp** [comment]
Nice, I didn't know the cypress tool yet, I'll definitely check it out.

To keep the original functionality, `mousedown` could also put the autocomplete in a "selecting" state so that the `blur` can know if it should close the menu or not. The flag would then have to be removed in `mouseup`  and `mouseout` to catch drag-off while clicking. Are there other edge cases?

**Comment by johanhalse** [comment]
Alright, finally fixed in https://github.com/varvet/tiny-autocomplete/releases/tag/v1.0.0
Thanks for your patience!
